layerai/sdk

renovate.json5
Currently only keeping `layer-api` updated.
=> Add renovate config

layer/utils/grpc/channel.py
=> Revert "Increase retry timeout to 30s"

README.md
=> Fix Code of Conduct link

.github/workflows/check.yml, .github/workflows/release.yml, Makefile, layer/pandas_extensions.py
Observe that reverting #48 caused this to fail [here](https://github.com/layerai/sdk/runs/6608771451?check_suite_focus=true)
=> Add a simple check to confirm the package loads without dev dependencies

test/unit/test_model_flavor.py, test/unit/test_train.py
Ignore all tests segfaulting on Mac M1.
=> Ignore all tests segfaulting on Mac M1

layer/decorators/dataset_decorator.py
Document pandas data frame types in the datasets.
=> Document pandas data frame types in the datasets

.github/workflows/check.yml, .github/workflows/release.yml, Makefile
Reverts layerai/sdk#69
We are having too many false positives as some lines appear to be covered in some tests runs but not all of them.
=> Revert "Integrate with codecov.io"

layer/logged_data/log_data_runner.py, layer/main.py, test/unit/logged_data/test_log_data_runner.py
This make it slightly convenient to log tabular data, as an alternative to `pandas.DataFrame`.
=> Support dict for layer.log

CONTRIBUTING.md, layer/flavors/base.py, layer/flavors/custom.py, layer/main.py
A couple of minor things I stumbled upon when working with sdk codebase.
=> Add minor doc fixes

test/e2e/test_log_types.py
Based on the previous review for #95
=> Minor cleanup in e2e tests

layer/logged_data/callbacks.py
Otherwise, layer fails on import
=> Make sure we have an XGBoost version higher than 1.3.0 for callbacks

layer/clients/project_service.py, poetry.lock, pyproject.toml, test/unit/projects/test_projects_service_client.py
At runtime, we want to fetch the contextual project by id based on env variable.
=> Add get_project_by_id for use in runtime

layer/main.py
Print a plain message while the notebook UI is turned off.
=> Print an execution progress message in notebooks on layer.run(...)

layer/clients/flow_manager.py, layer/clients/model_catalog.py, layer/clients/project_service.py, layer/main.py, layer/projects/init_project_runner.py, layer/projects/project_runner.py, layer/training/runtime/model_trainer.py, layer/training/train.py, poetry.lock, pyproject.toml, test/e2e/test_guest_user_reads.py, test/unit/grpc_utils/test_interceptors.py, test/unit/projects/test_init_project_runner.py, test/unit/projects/test_projects_service_client.py, test/unit/test_run.py, test/unit/test_train.py
More APIs support passing the project full name now so we can make the account explicit in more places
=> Upgrade to v0 9 365026

layer/clients/model_training_service.py, layer/projects/project_runner.py
=> Make model code location explicitly about version

layer/decorators/model_decorator.py
Fix model local train tracker stuck at "pending" at the end of a model train run.
=> Fix model local train tracker

layer/context.py, layer/global_context.py, layer/main.py, poetry.lock, pyproject.toml
We would like to warn users in case they're using an outdated version of the Layer Python SDK.
=> Version check for layer init and login

layer/decorators/dataset_decorator.py, layer/utils/runtime_utils.py, test/unit/utils/test_runtime_utils.py
To support https://www.notion.so/layerco/SDK-Devex-v1-0ee60206f0df4b70a98e379a60bc45ba#d2049beb08e940b98cf2cda25ae70f3a
After this gets merged, I'll follow up with a PR that uses this logic on the backend executors side.
=> Support list of dict-s as output of a dataset build function

layer/clients/data_catalog.py, layer/clients/model_catalog.py, layer/clients/model_training_service.py, layer/contracts/runs.py, layer/decorators/dataset_decorator.py, layer/decorators/definitions.py, layer/decorators/layer_wrapper.py, layer/decorators/model_decorator.py, layer/projects/execution_planner.py, layer/projects/progress_tracker_updater.py, layer/projects/project_runner.py, layer/resource_manager.py, test/e2e/test_resources.py, test/unit/decorators/test_dataset_decorator.py, test/unit/decorators/test_model_decorator.py, test/unit/projects/test_execution_planner.py, test/unit/projects/test_project_hash_calculator.py, test/unit/test_run.py
Consolidate function definitions
This PR is one of several to split https://github.com/layerai/sdk/pull/127 up. This PR should merge after #137 is merged.
=> Consolidate function definitions

pyproject.toml
For inspiration, see https://github.com/neptune-ai/neptune-client/blob/master/setup.py#L19 and https://github.com/wandb/client/blob/master/setup.py#L46
=> Update pyproject.toml for better PyPI metadata

layer/clients/executor_service.py, layer/clients/layer.py
=> Introduce Executor service client

.github/workflows/release.yml, poetry.lock
Trying to detect forks on `main` makes no sense so remove it.
=> Fix release pipeline

layer/training/runtime/system_metrics.py
Return immediately after catching the exception
=> Fix gpus logic

test/unit/test_version.py
Forgot to commit the test for https://github.com/layerai/sdk/pull/164 and it has been hanging out in my untracked files ever since
=> Add version test

layer/main.py, layer/projects/utils.py, test/unit/projects/test_utils.py
Add basic project name validation to layer init.
=> Add basic project name validation to layer.init

layer/executables/function.py, layer/executables/packager.py, test/unit/executables/test_function.py
Package function asset name, type, sdk version used to package the function, as well as function serialiser name and version.
=> Package function asset name, type and other metadata

layer/clients/account_service.py
Start using the new AccountAPI instead of the legacy UserAPI
=> Replace GetMyOrganization with GetMyAccountView

layer/clients/account_service.py, layer/clients/data_catalog.py, layer/clients/executor_service.py, layer/clients/flow_manager.py, layer/clients/layer.py, layer/clients/model_catalog.py, layer/clients/model_training_service.py, layer/clients/project_service.py, layer/clients/user_logs_service.py, layer/config/__init__.py, layer/config/config.py, layer/config/config_client.py, layer/utils/grpc/channel.py, test/unit/decorators/util.py, test/unit/projects/test_projects_service_client.py, test/unit/test_config.py, test/unit/test_config_client.py
Remove legacy service config classes, that are not relevant anymore, as there's always a single gRPC gateway address.
=> Remove individual service configs

.github/workflows/check.yml, CONTRIBUTING.md, Makefile, layer/main.py
Example at the bottom of this page: https://github.com/layerai/sdk/actions/runs/2744934691
=> Upload e2e-test logs

.flake8, Makefile, environment.Makefile, mypy.ini, poetry.lock, pyproject.toml
- Jupyter installed as a dev dependency.
- Create an ipython profile and add a file to always run autoreload extension
- Fix auto `make help` generation
- Add `make jupyter` that will start jupyter notebook in the terminal with editable layer package installed
=> INF-1204 - Add a make jupyter command to SDK

layer/executables/runtime.py, test/unit/executables/test_runtime.py
Support remote executable paths in `layer_runtime` module.
=> Support remote executable paths in layer_runtime

layer/auth.py, layer/config/config_manager.py, poetry.lock, test/unit/test_auth.py
Send audience from the SDK during login to fix issues when logging into an organization
Fixes #284.
=> Send audience from the SDK during login

layer/executables/layer_runtime.py, test/e2e/test_layer_runtime.py
Train models in `layer_runtime` module. Invocation similar to datasets:
```bash
python -m layer.executables.layer_runtime --project=layer/layer-runtime-55 ./train_model
```
=> Train models in layer_runtime

layer/decorators/model_decorator.py, layer/training/runtime/model_trainer.py, test/unit/decorators/test_model_decorator.py
Allow passing in args and kwargs for model training
=> Allow passing in args and kwargs for model training

layer/decorators/conda_decorator.py
Add documentation for Conda decorator
=> Add Conda decorator docs

layer/contracts/logged_data.py, test/unit/logged_data/test_log_data_runner.py
=> Fix tensor reshape for image logging

test/e2e/test_log_types.py
Removed in https://github.com/layerai/sdk/pull/232
=> Add remote logging E2E test

layer/logged_data/log_data_runner.py, layer/main.py, test/e2e/test_log_types.py, test/unit/logged_data/test_log_data_runner.py
Final piece for https://github.com/layerai/roadmap/issues/4
=> Support logging numpy arrays

.github/ISSUE_TEMPLATE/community-request.md
Add the issue template for community requests
=> Add the issue template for community requests

layer/logged_data/loggers/pytorch_lightning.py
Init project and login on Logger init
=> Fix PL Logger Init

CONTRIBUTING.md, Makefile
Add details on colab tests and integration.
Add details on jupyter notebook command
Clean up makefile since we no longer have a local built colab-lite image
Update makefile commands
=> Bring CONTRIBUTING.md up2date with latest devex improvements

layer/executables/entrypoint/common.py, layer/executables/packager.py, layer/executables/runtime.py, layer/projects/progress_tracker_updater.py, layer/projects/project_runner.py, test/unit/executables/test_packager.py
Fix progress reporting and dependency installs for remote runs.
=> Fix executable remote runs

layer/logged_data/log_data_runner.py
Fixes https://github.com/layerai/sdk/issues/333
We are seeing issues with unstable connections as uploading the logged data errors out and breaks the whole run.
Add a retry on timeout or rate limit with a 0, 0.5, 1, 2, 4 seconds delay.
=> Add retries to logged data uploads

layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model.py
Fixes the asset name (simple name) that should be asset path.
Also fixes the model task type.
=> fix metadata for train

layer/config/__init__.py, test/unit/test_config.py
Enable executables for all non production environments.
=> Enable executables for all non production environments

layer/context.py, layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model_trainer.py, layer/main/asset.py, layer/training/runtime/model_trainer.py, test/e2e/test_function_model_run.py, test/unit/test_context.py
Next PRs:
- Provide `get_url()` from context to address https://github.com/layerai/sdk/issues/314
- Add `__exit__` hooks for graceful termination
=> Manage active context via context manager and simplify execution code

layer/clients/__init__.py, layer/clients/data_catalog.py, layer/clients/model_catalog.py, layer/contracts/datasets.py, layer/contracts/logged_data.py, layer/contracts/models.py, layer/logged_data/log_data_runner.py, layer/main/asset.py, layer/main/log.py, layer/training/runtime/system_metrics.py, test/unit/contracts/test_logged_data.py, test/unit/decorators/util.py, test/unit/logged_data/test_log_data_runner.py, test/unit/test_dataset.py
Add API for getting logged data associated to a Model.
Refactored some code to avoid circular dependencies.
Fixes https://github.com/layerai/roadmap/issues/1
=> Add API for getting logged data associated to a Model

test/e2e/test_function_dataset_run.py, test/e2e/test_function_model_run.py
=> Fix e2e tests

layer/__init__.py, layer/clients/data_catalog.py, layer/clients/dataset_service.py, layer/contracts/datasets.py, layer/contracts/models.py, layer/flavors/base.py, layer/flavors/catboost.py, layer/flavors/custom.py, layer/flavors/huggingface.py, layer/flavors/keras.py, layer/flavors/lightgbm.py, layer/flavors/pytorch.py, layer/flavors/sklearn.py, layer/flavors/tensorflow.py, layer/flavors/xgboost.py, layer/logged_data/log_data_runner.py, layer/main/version.py, mypy.ini, poetry.lock, pyproject.toml
Lazy load ML dependencies (`torch`, `keras`, `xgboost`) in the `__init__` to lower the import times when the libs are not used. Also, `pandas` and `pyarrow` imports were moved from the module tops into the methods.
Before the change (with `torch` installed):
```bash
python -c "import layer"  3.52s user 0.77s system 128% cpu 3.325 total
```
After the change:
```bash
python -c "import layer"  1.95s user 0.44s system 214% cpu 1.114 total
```
IMHO there're still to much being done in the `__init__` and could be improved further, but that's a good start. Some data on what's going on (using [importtime_output_wrapper](https://pypi.org/project/importtime-output-wrapper/) to format the output):
```bash
python -m importtime_output_wrapper -m layer --depth 8 --width 600 --time cumulative --format …
```
=> Lazy load ML dependencies in the __init__

layer/__init__.py, layer/clients/data_catalog.py, layer/clients/dataset_service.py, layer/contracts/datasets.py, layer/contracts/models.py, layer/flavors/base.py, layer/flavors/catboost.py, layer/flavors/custom.py, layer/flavors/huggingface.py, layer/flavors/keras.py, layer/flavors/lightgbm.py, layer/flavors/pytorch.py, layer/flavors/sklearn.py, layer/flavors/tensorflow.py, layer/flavors/xgboost.py, layer/logged_data/log_data_runner.py, layer/main/version.py, mypy.ini, poetry.lock, pyproject.toml
Publishing to `pip` fails with direct dependencies:
```
HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'lazy-loader @ git+https://github.com/layerai/lazy_loader.git@26aa52ab057afb0c3f85ffc64f220eae0e9a222c'
```
=> Revert "Lazy load ML dependencies in the __init__ (#346)"

layer/context.py, layer/contracts/asset.py, layer/contracts/definitions.py, layer/executables/entrypoint/common.py, layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model.py, layer/main/asset.py, layer/main/log.py, layer/tracker/ui_progress_tracker.py, layer/training/runtime/model_trainer.py, test/unit/contracts/test_asset.py, test/unit/test_context.py
Fixes https://github.com/layerai/sdk/issues/314
=> Provide get_url() from context so user can go to current experiment url

layer/contracts/datasets.py, layer/contracts/logged_data.py, layer/contracts/models.py, layer/logged_data/log_data_runner.py, layer/main/log.py
Fixes https://github.com/layerai/roadmap/issues/2
=> Add support for logging to older dataset builds and model trains

layer/logged_data/immediate_logged_data_destination.py, layer/logged_data/logged_data_destination.py, layer/logged_data/queuing_logged_data_destination.py, layer/training/runtime/model_trainer.py, test/unit/logged_data/test_queuing_logged_data_destination.py
This PR addresses outstanding review items from here: https://github.com/layerai/sdk/pull/347
* make timeout significantly bigger (to confirm with product?)
* rename `get_logging_errors` to `close_and_get_errors`
* pulled up `get_logged_data` to common ancestor
* fixed types and typos :)
* added one unit test. I am not sure if at the level of unit tests we can do much better, but open to suggestions in the future.
Not done:
* `receive` is not renamed. Leaving it up to you @cihati to rename if you want - I couldn't think of anything better. `log_data` etc seems overloaded already.
=> Polish QueuingLoggedDataDestination implementation

layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model.py
Accept any kwargs to the run functions to enable backwards compatible changes to the runners.
=> Accept any kwargs to the run functions

layer/executables/entrypoint/common.py, layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model.py
Add queueing logged data destination to entrypoints
=> Add queueing logged data destination to entrypoints

layer/clients/model_catalog.py, layer/context.py, layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model.py, layer/main/asset.py, layer/training/base_train.py, layer/training/runtime/model_trainer.py, layer/training/train.py, test/e2e/test_function_dataset_run.py, test/unit/test_context.py, test/unit/test_train.py
Fixes #244 
Already available for models, this allows logging data to Layer without sharing the underlying dataset with Layer
=> Allow empty return for datasets

test/e2e/test_log_types.py
for https://github.com/layerai/roadmap/issues/1 and https://github.com/layerai/roadmap/issues/2
If we had this test, we would have caught https://github.com/layerai/sdk/pull/364
=> E2E test for get_metadata and logging on old datasets

layer/logged_data/system_metrics.py
Reverts layerai/sdk#382
Dimitar: 
Found a problem with the SDK cgroups change while testing my PR to always use the local sdk in the executors:
I get FileNotFoundError: [Errno 2] No such file or directory: 'stat' - I think the executors use distroless images so no binaries are available
=> Revert "Handle both cgroups v1 and v2 for system metrics"

layer/clients/project_service.py, test/e2e/conftest.py
To account for the leaked e2e test projects
=> Delete e2e test projects older than one day

layer/logged_data/system_metrics.py
Log warnings when metrics cannot be found on the system, note that this can lead to many warnings clogging up the Execution Logs.
When individual metrics cannot be found, do not log the metric. E.g. If max CPU cannot be gathered, CPU metrics aren't logged, but Memory/GPU are.
=> Only return the system metrics which can be found

layer/logged_data/log_data_runner.py, test/unit/logged_data/test_log_data_runner.py
Start logging dicts as grouped logs
=> Start logging dicts as grouped logs

layer/context.py, layer/contracts/tracker.py, layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model.py, layer/main/asset.py, layer/projects/progress_tracker_updater.py, layer/projects/project_runner.py, layer/tracker/asset_column.py, layer/tracker/non_ui_progress_tracker.py, layer/tracker/progress_tracker.py, layer/tracker/ui_progress_tracker.py, test/unit/tracker/test_progress_tracker.py
Refactor the progress tracker to be non-asset-specific and allow further refactoring of executable entrypoints
=> Refactor the progress tracker to be non-asset-specific

layer/clients/data_catalog.py, layer/clients/flow_manager.py, layer/clients/model_catalog.py, layer/clients/protomappers/aws.py, layer/clients/protomappers/datasets.py, layer/clients/protomappers/models.py, layer/clients/protomappers/runs.py, layer/context.py, layer/contracts/asset.py, layer/contracts/aws.py, layer/contracts/datasets.py, layer/contracts/models.py, layer/contracts/runs.py, layer/exceptions/exceptions.py, layer/executables/entrypoint/dataset.py, layer/executables/entrypoint/model.py, layer/logged_data/loggers/pytorch_lightning.py, layer/logged_data/system_metrics.py, layer/main/asset.py, layer/main/log.py, layer/projects/project_runner.py, layer/projects/ray_project_runner.py, layer/training/train.py, layer/utils/s3.py, test/e2e/test_function_model_run.py, test/e2e/test_guest_user_reads.py, test/e2e/test_log_types.py, test/unit/test_context.py, test/unit/test_dataset.py
Add domain objects and proto mappers to prepare for the executable entrypoints refactor
=> Add domain objects and proto mappers

layer/contracts/runs.py, layer/decorators/resources_decorator.py, layer/logged_data/data_logging_request.py, layer/logged_data/immediate_logged_data_destination.py, layer/logged_data/log_data_runner.py, layer/logged_data/logged_data_destination.py, layer/logged_data/queuing_logged_data_destination.py, test/unit/decorators/test_resources_decorator.py
Fix logging file uploads for queued logs. This fixes an issue that caused videos to not render in the web UI
Fixes LAY-3766
=> Fix logging file uploads for queued logs

layer/clients/label.py, layer/clients/layer.py, layer/context.py, layer/executables/entrypoint/common.py, layer/global_context.py, layer/main/run.py, layer/projects/init_project_runner.py, poetry.lock, pyproject.toml, test/unit/logged_data/test_logged_data_service_client.py, test/unit/test_global_context.py
We introduce labels from `layer.init` and applied in each function run.
The Backend is not fully operational yet but this already allows some testing and feedback collection.
Was tested with https://github.com/layerai/monorepo/pull/6726
=> Add labels PoC

layer/logged_data/system_metrics.py
I some cases (like colab) `/sys/gcroups/user.slice` doesn't actually exists. In this case, fall back to `/sys.cgroups` as the runtime is not limited in a user session.
=> Account for user.slice missing in cgroups

poetry.lock, pyproject.toml, test/e2e/assertion_utils.py
Fix Colab keras incompatibility
=> Fix protobuf transitive dependency version issue

layer/clients/executor_service.py, layer/config/config.py, layer/config/config_manager.py, layer/main/run.py, layer/projects/ray_workflow_project_runner.py, poetry.lock, pyproject.toml
- Refresh configuration as well in case of refresh
- Add grpc channel credentials
=> Adapt executor api changes 
