layerai/sdk

CONTRIBUTING.md
poetry.lock
pyproject.toml

Pre-requirements for tests to work on M1
- Conda installed
- Conda environment created with `conda create -yq -n sdk-test python=3.8 tokenizers==0.12.1 xgboost==1.5.1 lightgbm==3.3.2 poetry h5py==3.6.0 pyarrow==7.0.0`
- `conda activate sdk-test`

SDK M1 tests

---

.github/workflows/check.yml
CONTRIBUTING.md

A common mistake is editing the dependencies in `pyproject.toml` without updating the lock file. Adding a github check that guards against that.

Add check to ensure we keep the poetry lock up to date

---

.github/workflows/release.yml

In https://github.com/layerai/sdk/pull/12 we've added the same check on PRs. However if two PRs both edit the lockfile, they can be green, but then the actual lockfile on `main` is not up to date.
Run the same check on `main` to ensure we catch that degenerate case.

Check that lockfile is updated on main

---

layer/utils/grpc/channel.py

Increase retry timeout to 30s to improve reliability of long running jobs

Increase retry timeout to 30s

---

layer/pandas_extensions.py
test/unit/test_pandas_extensions.py

Do not require `Tuple[Image, ...]` in `Images.__init__`.
The `Tuple` requirement now implies the data should be always copied, which might not always be efficient. Loosen the restriction by requiring only `Sequence[Image]` instead, as only `len` and `__get_item__` implementations are required for conversions.

Use sequence instead of tuple

---

layer/pandas_extensions.py
test/unit/test_pandas_extensions.py

Implement concat same type for pandas `Images`. Pandas might call this method for larger data frames.

Concat same type for pandas Images

---

layer/pandas_extensions.py
test/unit/test_pandas_extensions.py

Fix `Images` type being registered for every pandas type name. The snippet:
```python
df = pd.DataFrame({"col1": (1, 2, 3, 4)})
df.dropna(how="all", inplace=True)
```
that has nothing to do with the `Images`  type, results in
```
TypeError: '>' not supported between instances of 'Images' and 'int'
```

Fix error: '>' not supported between instances of 'Images' and 'int'

---

poetry.lock
pyproject.toml

Resolves https://github.com/layerai/sdk/security/dependabot/2

Pin docker to v4 to ensure we don't pull a vulnerable pywin32 version

---

Makefile

By default poetry won't uninstall a package if it is completely removed as a dependency. Because of this, I almost deleted a required dependency in https://github.com/layerai/sdk/pull/35
Force poetry to remove packages and only use dependencies in the lock file.

Ensure removed dependencies get cleaned up from poetry vevn

---

layer/__init__.py
layer/pandas_extensions.py
test/unit/test_pandas_extensions.py

Add multidimensional `numpy` array support in layer datasets.
Arrays must be wrapped with the `layer.Arrays` class to provide the conversions between the `numpy.ndarray ` and `arrow` types. Numpy arrays are serialised to `pyarrow.binary` type, using [numpy.save](https://numpy.org/doc/stable/reference/generated/numpy.save.html) and deserialised using [numpy.load](https://numpy.org/doc/stable/reference/generated/numpy.load.html).
```python
import pandas as pd
import numpy as np
import layer
from layer.decorators import dataset
@dataset("ndarrays_demo")
def build():
return pd.DataFrame(
{
"array": layer.Arrays(
(
np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64),
np.array([[7, 8, 9], [10, 11, 12]], dtype=np.int64),
np.array([[13, 14, 15], [16, 17, 18]], dtype=np.int64),
)
)
},
copy=False,
) …
```

Add numpy ndarray serialisation to arrow

---

Makefile
poetry.lock
pyproject.toml

Remove pillow dependency from SDK, to avoid unnecessary version constraint conflicts. Only instance checks are made on `PIL`.

Remove pillow dependency from SDK

---

Makefile

Poetry won't create a virtual env if already inside one. This means that we can't do `poetry install --remove-untracked` as this removes poetry itself from the virtual environment.
[Poetry issue](https://github.com/python-poetry/poetry/issues/4055)

Don't remove untracked if in a venv

---

layer/pandas_extensions.py

Lazily import `pillow`, so that `import layer` does not fail if it is not available.

Lazily import pillow

---

test/e2e/test_pandas_images_dataset.py

Add Pillow dependency to the images e2e test to be able to remove it from the python runtime in the backend.

Add Pillow dependency to the images e2e test

---

layer/pandas_extensions.py
test/unit/test_pandas_extensions.py

Fix pandas describe crashing if `layer.Images` or `layer.Arrays` types are used.
Unique values for `layer.Images` and `layer.Arrays` are not counted for now, and always returns all values unique.

Fix pandas describe for Images and Arrays 

---

layer/flavors/custom.py

Tests couldn't cover this case as the `tmp_path` passed to the test function created already.

Fix custom model serialization

---

layer/pandas_extensions.py

Add docstrings to `layer.Images` and `layer.Arrays` classes.

Add docstrings to Images and Arrays classes

---

layer/clients/data_catalog.py
layer/pandas_extensions.py
test/unit/test_pandas_extensions.py

With this change, there is no need to wrap pandas data frame image or ndarray columns into `layer.Images` or `layer.Arrays`. Instead, `store_dataset` will figure this out by checking if the instances are `PIL.Image.Image` and `numpy.ndarray` and do the conversion automatically.

Implicitly convert images and ndarrays

---

layer/clients/model_catalog.py
layer/contracts/models.py
layer/flavors/base.py
layer/flavors/catboost.py
layer/flavors/custom.py
layer/flavors/huggingface.py
layer/flavors/keras.py
layer/flavors/lightgbm.py
layer/flavors/pytorch.py
layer/flavors/sklearn.py
layer/flavors/tensorflow.py
layer/flavors/utils.py
layer/flavors/xgboost.py
layer/main.py
layer/training/base_train.py
layer/training/train.py
layer/types.py
test/unit/test_load_model_cache.py
test/unit/test_model_flavor.py

Introduce a `Model.predict(input_df: pandas.Dataframe) -> pandas.Dataframe` API.
Implemented for sci-kit learn and catboost models.

Add model prediction API

---

test/__init__.py
test/unit/test_model_flavor.py
test/unit/test_train.py

Skip segfaulting tests only on Mac M1. Related to suggestion in https://github.com/layerai/sdk/pull/62#discussion_r883413545.
Doing a substring check, as other methods still return i386 when run through `Rosetta` emulation.

Skip segfaulting tests only on Mac M1

---

layer/logged_data/log_data_runner.py
test/unit/logged_data/test_log_data_runner.py

LAY-3207
Previously, we allows any `Path` to be saved directly to S3. With this change, we explicitly check for the file extension. This will be even more necessary when we add video support to differentiate between different `Path` objects.

Support GIF for layer.log

---

layer/flavors/custom.py
test/unit/common/dummy_model.py
test/unit/test_custom_model.py
test/unit/test_model_flavor.py

Previous custom model pickle routine was using Cloudpickle which was causing errors to load a custom model in different python versions. Now we use plain pickle to serialize and load the model.

Fix custom model pickling

---

CONTRIBUTING.md

Fix current instructions on M1 pre-requirements. We expected conda to be used based on Apple recomendation of Miniforge3 from conda-forge. This will ensure that `make install` and `make test` work correctly on Apple M1 devices.

Clarify pre-requirements to use SDK with Apple M1 devices

---

CONTRIBUTING.md
Makefile

Avoid requiring specific package versions added manually to Conda environment and detect correct environment is available

Simplify setup pre-requirements on Apple arm processors

---

layer/tracker/output.py

Rendering the progress ui in Google Colab appears to cause crashes due to an identified version mismatch.
Disable the progress UI in jupyter temporarily until we find a proper solution

Disable jupyter rich rendering

---

layer/clients/logged_data_service.py
layer/contracts/logged_data.py
layer/logged_data/log_data_runner.py
layer/main.py
test/e2e/test_log_types.py
test/unit/logged_data/test_log_data_runner.py
test/unit/logged_data/test_logged_data_service_client.py

Previously, the `step` argument of `layer.log` only worked for numeric values. As of this change, we also support images as well (both PIL.Image and image files)

Step support for log.layer IMAGE

---

layer/clients/data_catalog.py
test/unit/test_get_batch_chunks.py

Instead of having a hardcoded chunk size set to a very small value, compute the chunk size of the batch dynamically. This should significantly improve the throughput for `store_dataset`.

Compute number of rows per batch slice dynamically

---

layer/main.py
layer/tracker/output.py
layer/tracker/progress_tracker.py

Tested on Google Colab and local Jupyter notebook environments that it works.
The clearing of the logging handlers seems to be non-disruptive, and it's effectively done as soon as you import the `mlflow` library anyway.

Fix rich UI in notebook environments

---

Makefile

For apple M1 devices poetry was not being properly validated for availability
Make it a task and set as dependency for install

Fix Makefile poetry dependency

---

poetry.lock
pyproject.toml

This is an unused dependency that clashes with the Colab runtime.
Before the change and output of installing layer sdk:
After the change and output of installing the layer sdk:

Remove sdk dependencies clashing with Colab runtime

---

layer/clients/model_catalog.py
layer/projects/project_runner.py

The `fabric` field has been removed from the proto API. 
This PR removes the use of that field from the SDK.

[LAY-3297] Align with the API signature

---

layer/global_context.py
layer/main.py

Check if the Python version is supported on the first remote call (when users call `layer.run`) since fetching models/dataset or running local builds/trains works in any Python version.

Check supported Python version

---

pyproject.toml

This is blocking release. The list: https://pypi.org/classifiers/

Fix the PyPI classifier

---

layer/__init__.py
layer/main.py
pyproject.toml

Calling `pkg_resources.get_distribution` inside Colab fails hard in the cases where we've upgraded packages without restarting the runtime.
We should fix the package conflicts it complains about as these are real, but for now avoid using it to unblock users.
Instead we add `pyproject.toml` to the package and get the version from there.

Read version from pyproject.toml to avoid using pkg_resources

---

layer/main.py
poetry.lock
pyproject.toml

It uses `pkg_resources` under the hood which fails hard when we upgrade a dependency on Colab without restarting the runtime.
Instead just query PyPi directly since this is quite a trivial request and a payload to parse.

Don't use luddite

---

test/__init__.py

`IS_DARWIN` returns a tuple which casts to `True` always and hence skips the tests in CI as well as local Linux.
Instead return a boolean.

Ensure IS_DARWIN evaluates to false on Linux

---

layer/main.py

Otherwise we always assume personal account when doing `layer.run` (hence ignoring the `layer.init` result)

Use project full name from context in layer.run

---

test/e2e/test_function_assertion_run.py

`test/e2e/test_function_assertion_run.py::test_remote_run_with_dataset_fails_when_assertion_fails` fail consistently with a timeout

Skip flaky test with Linear ticket ref

---

layer/contracts/logged_data.py

Only use numpy typing for type checking. This should resolve errors during training.

Only use numpy typing for type checking

---

layer/tracker/asset_column.py

Adjusts the status color to gray, which is readable in both CLI, light and dark notebook themes.

Adjust description color for SDK UI

---

poetry.lock
pyproject.toml

Use [mlflow-skinny](https://github.com/mlflow/mlflow/blob/master/README_SKINNY.rst) which comes without all the UI and SQL support.
Add `scipy` directly as it is needed for `mlflow.sklearn` as per the `mlflow` docs 
Removes the following dependencies bloat:
```
• Removing alembic (1.8.0)
• Removing docker (4.4.4)
• Removing flask (2.1.2)
• Removing greenlet (1.1.2)
• Removing gunicorn (20.1.0)
• Removing importlib-resources (5.8.0)
• Removing itsdangerous (2.1.2)
• Removing mako (1.2.0)
• Removing prometheus-client (0.14.1)
• Removing prometheus-flask-exporter (0.20.2)
• Removing querystring-parser (1.2.4)
• Removing sqlalchemy (1.4.39)
• Removing sqlparse (0.4.2)
• Removing websocket-client (1.3.3)
```

Use mlflow-skinny

---

.github/workflows/check.yml
.github/workflows/release.yml

Potentially related to https://github.com/python-poetry/poetry/issues/5967 , we are seeing unstable results when running `poetry lock --no-update`.
To unblock CI, disable this check for now until we get to the bottom of it.

Disable lockfile checks

---

poetry.lock
pyproject.toml

Fix `poetry` complaining on invalid dependency constraint:
```
poetry lock --no-update
Resolving dependencies... (1.8s)<debug>PackageInfo:</debug> Invalid constraint (importlib-metadata (>='4.4') ; python_version < "3.10") found in markdown-3.3.5 dependencies, skipping
Resolving dependencies... (2.5s)<debug>PackageInfo:</debug> Invalid constraint (importlib-metadata (>='4.4') ; python_version < "3.10") found in markdown-3.3.5 dependencies, skipping
...
Resolving dependencies... (29.2s)
```
which comes from the `markdown` (https://github.com/python-poetry/poetry/issues/4777).
The issue was fixed in `markdown=3.3.6` (see https://github.com/Python-Markdown/markdown/pull/1197). However, `markdown=3.3.6` is not compatible with `flake8` `^4.0.1`, so a downgrade is required.

Fix markdown invalid dependency constraint

---

layer/decorators/dataset_decorator.py
layer/executables/dataset/entrypoint.py
layer/projects/project_runner.py
test/unit/decorators/test_dataset_decorator.py

Extract dataset and model function registrations into single `register_function` function. Make `register_dataset_function` and `register_model_function` "private", to deprecate their use in SDK. This is a step towards function runtime unification.

Refactor function registration into generic function

---

layer/projects/progress_tracker_updater.py
layer/projects/project_runner.py
layer/tracker/asset_column.py
layer/tracker/non_ui_progress_tracker.py
layer/tracker/progress_tracker.py
layer/tracker/ui_progress_tracker.py

Properly display asset statuses in the sdk's notebook UI.

Fix asset statuses in sdk notebook UI 

---

layer/decorators/dataset_decorator.py
layer/decorators/model_decorator.py

Defer function metadata capture and packaging of dataset and model decorators to runtime. Now, all is done during the wrapper calls, which makes it difficult to have a single runtime for dataset builds and model trains. In case of executables, the decorators would only gather runtime info.
As a side effect, will close [LAY-3127](https://linear.app/layer/issue/LAY-3127/dataset-decorator-always-requiring-project).

Defer function metadata capture and packaging to runtime

---

layer/executables/function.py
layer/settings.py
test/unit/executables/test_function.py

Capture function metadata from the decorators and package them into the executable. Usage:
```python
@dataset("test_dataset")
@resources("path/to/resource", "path/to/other/resource")
@pip_requirements(packages=["package1", "package2==0.0.42"])
def dataset_function():
return [42]
function = Function.from_decorated(dataset_function)
function.package()  # returns the path to the executable
```
Only `dataset`, `model`, `resources` and `pip_requirements` are relevant to the execution (assertions are relevant too, but will be implemented later). `fabric` decorator is the property of a runtime, hence it is not packaged.

Capture function metadata from decorators into the executable

---

layer/clients/project_service.py
test/unit/projects/test_projects_service_client.py

When reading a `ProjectMessage` use new `account_id` instead of deprecated (to be removed) `organization_id`. 'account_id` is already returned by our Project APIs.

Switch to using account_id instead of organization_id from Project message

---

layer/executables/cloudpickle/LICENSE
layer/executables/cloudpickle/__init__.py
layer/executables/cloudpickle/cloudpickle.py
layer/executables/cloudpickle/cloudpickle_fast.py
layer/executables/cloudpickle/compat.py
layer/executables/packager.py
pyproject.toml
test/unit/executables/test_packager.py

Embed cloudpickle `2.1.0` into the executable archive, so the package can load the user function by itself, without installing any external dependencies. Dependency installs are removed from the executable and will be handled by the runtime.

Embed cloudpickle into executable

---

layer/executables/packager.py
layer/executables/runtime.py
test/unit/executables/test_packager.py
test/unit/executables/test_runtime.py

Skeleton contract between the function executable package and the runtime.
Basically, when started, the executable package asks for the runtime available by trying to call a global `__function_runtime` attribute. If one is provided, the executable will pass the loaded function to the runtime for execution.
All runtime implementations will extend the `BaseFunctionRuntime` class, which is a skeleton of a function execution workflow.
More concrete implementations will follow.

Implement base function runtime

---

layer/executables/packager.py
test/unit/executables/test_packager.py

Support storing arbitrary metadata inside the executable package by adding `metadata: Optional[Dict[str, Any]]` argument to a `package_function` function.
Required to capture asset names and types for the dataset and model builds.

Package executable metadata

---

layer/clients/account_service.py
layer/clients/data_catalog.py
layer/clients/executor_service.py
layer/clients/flow_manager.py
layer/clients/layer.py
layer/clients/logged_data_service.py
layer/clients/model_catalog.py
layer/clients/model_training_service.py
layer/clients/project_service.py
layer/clients/user_logs_service.py
layer/config/guest_login_client.py
layer/utils/grpc/channel.py
test/unit/decorators/util.py
test/unit/logged_data/util.py
test/unit/projects/test_projects_service_client.py
test/unit/test_dataset.py

There's a common pattern throughout the SDK to call an operation on the backend:
```python
with LayerClient(config.client, logger).init() as client:
client.data_catalog.list_datasets()
```
However, such snippet opens 10 SSL connections each time it is executed!
```bash
GRPC_VERBOSITY=debug GRPC_TRACE=all python ~/layer/1/layer_init.py 2>&1 | grep "grpc_secure_channel_create"
I0721 11:53:22.103882000 8644068864 chttp2_connector.cc:395]           grpc_secure_channel_create(target=grpc.development.layer.co:443, creds=0x6000023b83c0, args=0x307238730)
I0721 11:53:22.107976000 8644068864 chttp2_connector.cc:371]           grpc_secure_channel_create(target=grpc.development.layer.co:443, creds=0x6000036fde00, args=0x7febda1b7a40)
I0721 11:53:22.109439000 8644068864 chttp2_connector.cc:371] …
```

Reuse grpc channel in layer client

---

layer/clients/logged_data_service.py
layer/logged_data/log_data_runner.py
layer/main.py
test/unit/logged_data/test_log_data_runner.py
test/unit/logged_data/test_logged_data_service_client.py

Adds the `LoggedMetricGroupId` to the logged metrics request. Including this id will allow to group metrics together, so that later the UI can visualize multiple metrics in the same chart.

Add group uuid to logged metrics

---

Makefile

Improve developer experience by providing a simple one-liner to upgrade poetry after hard-failing due to a version mismatch.

Advise on how to upgrade poetry

---

.gitignore
CONTRIBUTING.md
Makefile
environment.Makefile
include.Makefile

Makes M1 macs work with other conda versions other than miniforge3
Splits Makefile to reduce complexity of one big file
Add a create and remove environment command to help users have a working conda env

INF-1211 Make virtualenv setup easier

---

layer/clients/data_catalog.py
layer/executables/layer_runtime.py
layer/executables/packager.py
layer/executables/runtime.py
layer/projects/project_runner.py
mypy.ini
test/e2e/test_layer_runtime.py

Layer function runtime for dataset builds. Usage:
```bash
python -m layer.executables.layer_runtime --help
usage: layer_runtime.py [-h] --project PROJECT [--api-url API_URL]
[--api-key API_KEY]
executable_path
Function runtime
positional arguments:
executable_path    the local file path of the executable
optional arguments:
-h, --help         show this help message and exit
--project PROJECT  project name
--api-url API_URL  api url. Optionally, LAYER_API_URL environment variable
is also supported
--api-key API_KEY  api key. Optionally, LAYER_API_KEY environment
variable is also supported
```

Layer function runtime for dataset builds

---

layer/clients/account_service.py
layer/config/config.py
layer/config/config_manager.py

- Authentication check on account should now be done on the new `account_id` jwt claim
- CreateOrganizationAccount and DeleteAccount are needed for e2e test setUp / teardown fixtures

Fix legacy auth check for account and add account creation / deletion methods to client

---

poetry.lock
pyproject.toml

Adjust the dependencies, so that Google Colab does not prompt to restart the Python runtime.

Adjust dependencies so Colab does not prompt to restart the runtime

---

layer/clients/executor_service.py
layer/executables/function.py
layer/executables/runner.py
layer/main.py
layer/projects/project_runner.py
test/e2e/test_remote_run.py
test/unit/executables/test_runner.py

Run layer functions remotely using executable packages.
The feature is not yet enabled and requires passing a feature flag to `layer.run(..., executables_feature=True)` or setting the environment variable `LAYER_EXECUTABLES=1` for the process.
Example:
```python
import layer
import pandas as pd
from layer.decorators import dataset, model
@dataset("dummy-dataset")
def build_dataset():
return pd.DataFrame({"a": [1, 2, 42]})
@model("dummy-model")
def train_model():
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
X, y = make_classification(
n_samples=1000,
n_features=4,
n_informative=2,
n_redundant=0,
random_state=0,
shuffle=False,
)
classifier = RandomForestClassifier(max_depth=2, random_state=0)
return classifier.fit(X, y) …
```

Run layer functions remotely using executables

---

layer/decorators/dataset_decorator.py
layer/decorators/model_decorator.py
layer/exceptions/exceptions.py
layer/executables/layer_runtime.py
layer/executables/packager.py
layer/executables/runtime.py
test/e2e/test_layer_runtime.py

Execute the same `layer_runtime` module for local runs.
Add the `__function_return_result` name to function package Python namespace to exchange the function return result with the runtime. It is safe to do so, as `__function_return_result` is isolated within the function package module and does not pollute the namespace of the main process.
The code is guarded by the `LAYER_EXECUTABLES=1` environment variable condition and is not executed by default.

Execute layer runtime locally

---

layer/tracker/output.py

This fixes most likely a race condition when stdout is redirected to the rich Console.

Do not redirect stdout to rich Console

---

test/e2e/test_guest_user_reads.py

One should not be able to create project as a guest

Implement E2E test for project init by guests

---

layer/__init__.py

Make assertion imports available from the layer module. This way, a user can simply run:
```python
import layer
@layer.assert_true
...
```

Make assertion imports available from the layer module

---

layer/__init__.py
layer/clients/model_catalog.py
layer/main/asset.py
layer/training/base_train.py
layer/training/runtime/model_trainer.py
layer/training/train.py
test/e2e/test_function_model_run.py

Make models optional to return from the model decorator.
This should address https://github.com/layerai/sdk/issues/244 by letting users return `None` from their training runs without impacting Layer successfully finishing a training run and collecting metadata.

Make models optional to return from the model decorator

---

layer/clients/logged_data_service.py
layer/logged_data/log_data_runner.py
layer/main/log.py
test/unit/logged_data/test_log_data_runner.py

Extend `layer.log` with a `category` parameter, so it can be used like `layer.log({...}, category="test")`.
This will be used in the Web UI to group the logged data on it.

Add category parameter when logging data

---

layer/executables/entrypoint/common.py
layer/executables/entrypoint/dataset.py
layer/executables/entrypoint/model.py

Adds support for reporting runExecutionMetadata to the flow manager when the specific output of the function is known, either a `dataset_build_id` or a `model_train_id`

[LAY-3690] Report function metadata

---

layer/projects/progress_tracker_updater.py

Fixes
```
layer.exceptions.exceptions.LayerClientException: code: INVALID_ARGUMENT, details: ModelVersionId.value invalid UUID string
```
when `LAYER_EXECUTABLES` feature enabled.

Fix invalid model train uuid for executables

---

layer/contracts/asset.py
layer/contracts/datasets.py
layer/contracts/models.py
layer/decorators/dataset_decorator.py
layer/decorators/layer_wrapper.py
layer/decorators/model_decorator.py
layer/settings.py
test/e2e/common_scenarios.py
test/unit/decorators/test_dataset_decorator.py
test/unit/decorators/test_model_decorator.py

One can now set descriptions for datasets & models using decorators. Because `get_dataset` and `get_model` does not return the full objects (i.e. it lacks description), this PR does not yet update E2E tests. I'll create a task to track this bigger issue, then E2E testing this behavior will be trivial 1-2 line change.
I did update unit tests & manually tested it E2E:

Add support for description for dataset and model decorators

---

test/e2e/test_log_types.py

Temporarily disable epoched_data e2e tests, to be enabled after some refactoring

Temporarily disable epoched_data e2e tests

---

layer/context.py
layer/contracts/asset.py
layer/executables/entrypoint/dataset.py
layer/executables/entrypoint/model_trainer.py
layer/global_context.py
layer/logged_data/loggers/pytorch_lightning.py
layer/main/asset.py
layer/main/log.py
layer/training/runtime/model_trainer.py
test/e2e/test_function_dataset_run.py
test/e2e/test_function_model_run.py
test/e2e/test_guest_user_reads.py
test/unit/contracts/test_asset.py
test/unit/test_context.py
test/unit/test_global_context.py

We want to give users contextual methods similar to the ones available inside a decorated layer function.
The end goal is to offer:
```python
def run_experiment():
context = layer.get_context()
train_url = context.get_url()
context.log({key:value})
with layer.model("my-model"):
run_experiment()
```
so that we are very close to Layer function executions
```python
@layer.model("my-model")
def run_experiment():
train_url = context.get_url()
layer.log({key:value})
```
This will help users a lot when they dont want to use decorators
-

Only keep read methods in Context

---

Makefile

This PR enables running the e2e tests using the new function execution system to ensure that all the tests are passing against the new implementation.

Force e2e tests to use the function execution system

---

layer/main/utils.py

Stop execution when trying to run the SDK on Windows without using WSL.

Fail fast when running on Windows without WSL

---

layer/context.py
layer/contracts/tracker.py
layer/logged_data/data_logging_request.py
layer/logged_data/file_uploader.py
layer/logged_data/immediate_logged_data_destination.py
layer/logged_data/log_data_runner.py
layer/logged_data/logged_data_destination.py
layer/logged_data/queuing_logged_data_destination.py
layer/logged_data/read_only_logged_data_destination.py
layer/main/asset.py
layer/main/log.py
layer/tracker/asset_column.py
layer/tracker/non_ui_progress_tracker.py
layer/tracker/progress_tracker.py
layer/tracker/ui_progress_tracker.py
layer/training/runtime/model_trainer.py
layer/training/runtime/system_metrics.py
test/unit/logged_data/test_log_data_runner.py
test/unit/logged_data/test_queuing_logged_data_destination.py

**Eventual Objective**: Log data in the background and do not interrupt execution if there is an error logging data. Attach error information (as a warning) to progress tracker's output in local mode.
**What this part doesn't do**: 
In this PR we're not changing any behaviour except for the added `close` call to http session when uploading files; new destination is not initialised in context yet and log function is falling back either to `ImmediateLoggedDataDestination` (which mimics current behaviour) or `ReadOnlyLoggedDataDestination` (which mimics current behaviour for the read part) based on execution context.
This PR just prepares classes so that they can be used by executables in next step, once new version of sdk is published.
**What this part does**: 
1) Introduce a concept of …

Log errors but do not stop executing on logging errors (part 1)

---

Makefile
layer/config/__init__.py
test/unit/test_config.py

Makes the function executable feature flag true by default but user override-able by explicitly setting it to `False`.
Let's chose between this option and https://github.com/layerai/sdk/pull/365 
@dpp23 @volkangurel

Flip the feature flag

---

renovate.json5

The dashboard is useful to trigger renovate to run on demand.
This will create a permanent issue with the list of dependencies Renovate manages. We will be able to trigger it to run by ticking a tickbox there.

Enable renovate dependency dashboard

---

layer/flavors/lightgbm.py
layer/flavors/xgboost.py
poetry.lock
pyproject.toml

Remove dependencies to ML frameworks:
* `scipy`
* `huggingface`
As they might not be always used, but still are installed as direct SDK dependencies.
It is now consistent similarly to e. g. `tensorflow`, which is not a direct SDK dependency, but model flavours depends on it lazily.

Remove ML framework dependencies

---

layer/__init__.py
mypy.ini
poetry.lock
pyproject.toml
test/conftest.py
test/unit/test_import.py

Bringing back lazy loads reverted in https://github.com/layerai/sdk/pull/356, because of pip not supporting publishing packages referencing git commit hashes.
Support for Python 3.7 was added in https://github.com/scientific-python/lazy_loader/pull/14, hence package is referenced by version now.
Not bringing back lazy loading pandas or numpy as they're always are loaded anyway, because of the [image extensions](https://github.com/layerai/sdk/blob/3a6b022982b542656bf0658a671f5b5d4af2302b/layer/__init__.py#L39).
Closes:
* https://linear.app/layer/issue/LAY-3689/lazilly-load-sdk-dependencies-that-are-not-always-needed
* https://linear.app/layer/issue/LAY-3341/import-kerascallback-and-xgboostcallback-lazily

Lazy load ML dependencies

---

layer/logged_data/system_metrics.py

On Ubuntu 22.04, we fail when we try to parse `cgroups` data to determine system metrics. Until we fix it, ensure we always use `psutil` if on a remote run.

Always fallback to psutil for system metrics on local runs

---

CONTRIBUTING.md
layer/executables/packager.py
layer/main/version.py
pyproject.toml
test/colab/test_import_login_init.ipynb
test/unit/executables/test_packager.py

In order to be able to be able to install the same version as the client side inside the remote executors.
In production, this means adding a file with the requirement `layer==1.2.3`, in development this means copying the local sdk code so we can install from source.

Bundle local sdk version in executable package

---

layer/main/utils.py

All sdk functions currently show as `Any->Any` as the `sdk_function` decorator masks their signature. This has also broken the automatic docs generation.

Preserve signature of sdk functions

---

layer/clients/account_service.py
layer/config/config.py
test/e2e/conftest.py
test/unit/config/test_config.py

Current API only gives the date without the time, so accounts older than one day are removed.
If we want older than one hour, we need to the update account api first to support more precise datetime.

Delete old test org accounts before running e2e tests

---

layer/logged_data/system_metrics.py

On my machine, `user.slice/memory.high` seems to have an extra empty line at the end of the file so the string comparison was failing.

Fix cgroups parsing on Ubuntu 22.04

---

layer/clients/account_service.py
test/e2e/conftest.py

We will test creation flow and access separately
Will clean up the code once all stacks can use a permanent test org account

Use permanent test organization in e2e tests if it exists

---

layer/projects/ray_workflow_project_runner.py

`main` build is currently broken with
```
layer/projects/ray_workflow_project_runner.py:61: error: Argument "id" to "Run" has incompatible type "RunId"; expected "UUID"
Found 1 error in 1 file (checked 131 source files)
```
This PR should fix it.

Fix RunId type mismatch

---

layer/clients/data_catalog.py
layer/exceptions/status_report.py
layer/projects/progress_tracker_updater.py

Application-level errors resulting from the Dataset Build process are reported to the metadata store.
We want to display those specific errors to the user in a concise way. 
This PR "rewires" the Dataset Build result into the error reporting, falling back onto the job log in case we don't have a status.
(which could be the case for OOM errors, for example)
Model train will be done separately because we need an [extra endpoint in the backend](https://linear.app/layer/issue/LAY-3770/model-catalog-should-offer-a-getmodeltrainstatus-endpoint) to use the same method exploited here.

[LAY-3768] Rewire error reporting for Dataset build

---

layer/clients/model_catalog.py
layer/projects/progress_tracker_updater.py
poetry.lock
pyproject.toml

Adopts the newly introduced `GetModelTrainStatus` to report application-level errors captured during model training.

[LAY-3771] Report model errors

---

layer/logged_data/log_data_runner.py
layer/main/log.py

By setting the env variable 'LAYER_FEATURE_RUNS=True', we can now do
```
layer.init("my-project", labels=["l1"])
layer.log({"key": 1.0})
```

Allow logging data only for runs
